title: 风丶停息了吗
description: > # this means to ignore newlines until "baseurl:"
  buyizhiyou's on the breeze.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: buyizhiyou # add your name
author-img: weilai.jpg # add your photo
about-author:  Algorithmic Engineer In Image And DeepLearning. # add description
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: buyizhiyou # add your Github handle
social-email: buyizhiyou@gmail.com# add your Email address

# Disqus
discus-identifier: buyizhiyou # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
